### ISSUE TITLE
Crash with End Remastered

### ISSUE THREAD

**Issue by asdfwasdq** [DrexHD/VillagerConfig#19]
Crashing when generating a world with End Remastered present.

1.17.1 Minecraft
0.40.0 1.17 Fabric API
0.11.6 Fabric Loader
R4.1.0 End Remastered (Latest public)
2.1.4 VillagerFix (Latest public)

https://www.curseforge.com/minecraft/mc-mods/endremastered-fabric

[crash-2021-09-08_02.53.31-client.txt](https://github.com/DrexHD/VillagerFix/files/7127423/crash-2021-09-08_02.53.31-client.txt)

**Comment by DrexHD** [comment]
Fixed in Version 3.0.0
