### ISSUE TITLE
Trades not refreshing

### ISSUE THREAD

**Issue by dull4h4n** [DrexHD/VillagerConfig#22]
The 1.12 trades which lock and have a chance to refresh after each sale do not appear to be working.
Also, villagers leveling up is not refreshing them either.

**Comment by DrexHD** [comment]
Villagers do indeed not refresh upon leveling up (will be fixed in the next release). But I can't replicate trades not refreshing after each sale _(Note: The chance for trades to refresh is 20% per trade you make)_.

**Comment by dull4h4n** [comment]
I'll test further. I did a lot of trades with multiple villagers, haven't seen any of them refresh.

**Comment by dull4h4n** [comment]
Okay, maybe i was just getting unlucky on every villager i had transacted with, but I was able to brute force one by doing all their trades and eventually they refreshed.

**Comment by dull4h4n** [comment]
I'm noticing normal particles when trading, but not the big swirl particles. When a villager's inventory would refresh after a trade, it would give the big particle effect and was obvious. It's just not easy to identify whether the refresh has occurred.
