### ISSUE TITLE
Crash on trade

### ISSUE THREAD

**Issue by dull4h4n** [DrexHD/VillagerConfig#23]
Was trading a partial stack of zombie skin to cleric villager. Shift clicked the gem, but there was only enough for 1 gem. I do not know if this is relevant to the crash.
Other details, the villager is max level.

`
Container click
Oh - I know what I did wrong!

ClassCastException: class net.minecraft.class_1645 cannot be cast to class me.drex.villagerconfig.util.IMerchantEntity (net.minecraft.class_1645 and me.drex.villagerconfig.util.IMerchantEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @452e19ca)
at

TradeOutputSlot.handler$cee000$onTrade (Line 533)

at

TradeOutputSlot.onTakeItem (Line 59)

at

ScreenHandler.method_34249 (Line 414)

at

Optional.ifPresent (Line 178)

at

ScreenHandler.internalOnSlotClick (Line 412)

at

ScreenHandler.onSlotClick (Line 284)

at

ClientPlayerInteractionManager.clickSlot (Line 417)

at

HandledScreen.onMouseClick (Line 566)

at

HandledScreen.mouseClicked (Line 362)

at

MerchantScreen.mouseClicked (Line 322)

at

Mouse.method_1611 (Line 94)

at

Screen.wrapScreenError (Line 491)

at

Mouse.onMouseButton (Line 94)

at

Mouse.method_22686 (Line 165)

at

ThreadExecutor.execute (Line 101)

at

Mouse.method_22684 (Line 165)

at

GLFWMouseButtonCallbackI.callback (Line 36)

at

JNI.invokeV (Native Method)

at

GLFW.glfwPollEvents (Line 3101)

at

RenderSystem.flipFrame (Line 195)

at

Window.swapBuffers (Line 310)

at

MinecraftClient.render (Line 1142)

at

MinecraftClient.run (Line 733)

at

Main.main (Line 238)

at

NativeMethodAccessorImpl.invoke0 (Native Method)

at

NativeMethodAccessorImpl.invoke (Line 77)

at

DelegatingMethodAccessorImpl.invoke (Line 43)

at

Method.invoke (Line 568)

at

MinecraftGameProvider.launch (Line 608)

at

Knot.launch (Line 77)

at

KnotClient.main (Line 23)

at

NativeMethodAccessorImpl.invoke0 (Native Method)

at

NativeMethodAccessorImpl.invoke (Line 77)

at

DelegatingMethodAccessorImpl.invoke (Line 43)

at

Method.invoke (Line 568)

at

OneSixLauncher.launchWithMainClass (Line 210)

at

OneSixLauncher.launch (Line 245)

at

EntryPoint.listen (Line 143)

at

EntryPoint.main (Line 34)`

**Comment by dull4h4n** [comment]
Could not reproduce attempting same action.

**Comment by dull4h4n** [comment]
https://bytebin.lucko.me/83xRG5FK9B
https://bytebin.lucko.me/AVxDEP4QJM

Two more.

**Comment by dull4h4n** [comment]
Okay, reproduced with mason when I put exactly 30 clay balls in. Selected the gem at price of 10 clay balls. This seems to 100% cause.

**Comment by dull4h4n** [comment]
Happened with 44 clay balls offered for 10 clay purchase. Not finding the pattern on the numbers.

**Comment by DrexHD** [comment]
I haven't tested it, but it should be fixed in the latest commit.

**Comment by dull4h4n** [comment]
Good deal. Just actually had it happen with a straight up 10 offer for 10 required as well. Thanks!

**Comment by DrexHD** [comment]
> Good deal. Just actually had it happen with a straight up 10 offer for 10 required as well. Thanks!

Was that referring to the new commit or adding more information. Did that commit fix the issue for you?

**Comment by dull4h4n** [comment]
Sorry i posted that right as you put the commit up. Will test in a few.

**Comment by dull4h4n** [comment]
Seems solid. Traded with half dozen villagers like 20 times.
