### ISSUE TITLE
Suggestion: Value slider for sold goods

### ISSUE THREAD

**Issue by dull4h4n** [DrexHD/VillagerConfig#24]
Would be cool if there was a slider to increase or decrease value of goods across the board.
For instance, my priest buys 4 gold ingots for 1 emerald. If I had the slider set to +50%, it would increase the necessary gold to 6 ingots. A global slider would probably work, but a job based slider might be more utilized.

Also is the ability to blacklist items still available or was that done away with?

**Comment by DrexHD** [comment]
If you want to adjust any trades, you should use the data-driven trades, described in the [wiki](https://github.com/DrexHD/VillagerConfig/wiki). That way you can also remove / blacklist trades!
A slider wouldn't work, because there is no automatic way to detect if a trade is selling or buying.
