### ISSUE TITLE
Add support for REP?

### ISSUE THREAD

**Issue by Rushmore75** [DrexHD/VillagerConfig#26]
This mod is super cool and I thank yall for making it!

I am wondering if integration with https://modrinth.com/mod/roughly-enough-professions-rep is possible? Such as having the trades show up in the rei trades so players can view the newly configed trades?

( I don't know if it's you that would be compatible with them or them with you)

**Comment by DrexHD** [comment]
VillagerConfig only changes villager trades. This would fit better as a feature request for that mod.

**Comment by Rushmore75** [comment]
Ok
