### ISSUE TITLE
[Issue] worldgen registry error

### ISSUE THREAD

**Issue by kxkxrxtx** [DrexHD/VillagerConfig#27]
It seems there's some trouble with my modlist. I can't point what's the problem with it so I'm leaving the latest.log file hoping you can help me. Thank you! n_n

**Comment by kxkxrxtx** [comment]
[latest.log](https://github.com/DrexHD/VillagerConfig/files/9274697/latest.log)

**Comment by DrexHD** [comment]
Fixed in d8954c1e71aae000c42e257d21b254a0352951ed!
