### ISSUE TITLE
Unable to obtain trade

### ISSUE THREAD

**Issue by JAVAHTML1** [DrexHD/VillagerConfig#33]
I can't get my villagers to use the custom trades. Which work station do I use?

**Comment by DrexHD** [comment]
The work station depends on the [villager profession](https://minecraft.fandom.com/wiki/Villager#Professions). You currently can't add villager professions / work stations with this mod, so you can only edit / overwrite existing villager trades! If you need any further support with custom trades you should [join my support discord](https://discord.gg/HeZayd6SxF)!
