### ISSUE TITLE
1.20.1 Crashes on latest fabric loader version with latest villager config version

### ISSUE THREAD

**Issue by Rebel459** [DrexHD/VillagerConfig#35]
log here https://mclo.gs/VBuYzaL

didn't crash before updating villagerconfig and fabric loader

**Comment by DrexHD** [comment]
You are using the 1.20.2 version of VillagerConfig, but you are running 1.20.1! You can get the latest version for [1.20.1 on github releases](https://github.com/DrexHD/VillagerConfig/releases/tag/v4.0.3-1.20.1).

**Comment by Rebel459** [comment]
Wait, did i use the wrong instance lol.
My bad. I think the same issue happened on 1.20.1 too though when i upped just the loader version. Will investigate and open a new issue if it ends up it was still this mod. My bad on the really dumb mistake here

**Comment by A5ho9999** [comment]
The version 4.1.0+1.20.2 is marked as supporting 1.20 & 1.20.1 on Modrinth but you just get the error the OP provided when using it not on 1.20.2

**Comment by Rebel459** [comment]
Ah that’s probably a separate issue entirely

**Comment by ZiLenTz** [comment]
Same here.
I just tried 4.1.0 as it mentioned that all 1.20, 1.20.1 and 1.20.2 were supported and had no idea why it crashed.

Sorry for mentioning @DrexHD but in case that you missed that this version on CurseForge still includes 1.20 and 1.20.1.
