### ISSUE TITLE
Error on Generation in 1.20.1

### ISSUE THREAD

**Issue by Kamorzy** [DrexHD/VillagerConfig#36]
Running '/villagerconfig generate' outputs: 'An error occurred, please look into the console for more information.'

The log on the error is pasted [here](https://pastebin.com/Uk9zRgxG)

Its a modded instance with Cobblemon, VillageConfig, EasierVillagerTrading, and a bunch of client side mods if that matters.

**Comment by DrexHD** [comment]
What version of the mod are you using?

**Comment by Kamorzy** [comment]
Its 4.0.3+1.20.1

Fabric API 0.90.7+1.20.1, Fabric Loader 0.14.24. I tried it with a fresh instance without the other mods and it worked fine, so its a mod incompatibility. I tried removing Cobblemon and some optimization mods but it hasn't worked yet. I'll try to keep removing them to try to figure out which one it is.

**Comment by Kamorzy** [comment]
It seems to be an incompatibility with [Nature's Spirit](https://modrinth.com/mod/natures-spirit)
