### ISSUE TITLE
Incompatibility with End Remastered

### ISSUE THREAD

**Issue by NoThrottle** [DrexHD/VillagerConfig#39]
Environment:
- Minecraft Java 1.20.1
- Fabric 0.14.25
- VillagerConfig 4.0.3
- End Remastered 5.2.4

Generating the default data pack using `/villagerconfig generate` causes this error:
Unable to convert class com.teamremastered.endrem.items.ERTrades$EREyeTrade, generated json won't be complete!

Full Error:
https://gist.github.com/NoThrottle/5bf6bb740ed7820c05e8623fd650d29e

I'm unsure if the error is completely related/caused by EndRem since the warning seem to indicate that it can ignore End Remastered.

It is completely possible that an updated set of the mods and environment has fixed this issue.

**Comment by DrexHD** [comment]
This expected / intended behavior. VillagerConfig has code to convert vanilla trade "types" into it's own format. However it is impossible to do so for custom mods, that don't use vanillas trade types. You can recreate the same trades by adding
```json
{
  "cost_a": {
    "type": "minecraft:item",
    "name": "minecraft:emerald",
    "functions": [
      {
        "function": "minecraft:set_count",
        "count": {
          "min": 30,
          "max": 50
        }
      }
    ]
  },
  "cost_b": {
    "type": "minecraft:item",
    "name": "minecraft:rabbit_foot"
  },
  "result": {
    "type": "minecraft:item",
    "name": "endrem:evil_eye"
  },
  "trader_experience": 0
}
```
to the correct sections in the cleric and wandering trader trades.
See [ERTrades.java](https://github.com/Team-Remastered/End-Remastered-Fabric/blob/1.19.X/src/main/java/com/teamremastered/endrem/items/ERTrades.java) for the original trades!
