### ISSUE TITLE
Unable to generate default datapack: Index out of range

### ISSUE THREAD

**Issue by shvrma** [DrexHD/VillagerConfig#43]
The issue is present in both singleworld and on  dedicated server. [There is](https://modrinth.com/modpack/create-valley/version/IzRck4LL) a modpack used + VillagerConfig ver. 4.1.2+1.20.1 and Villager Converting ver. 1.2.1 for 1.20-1.20.1. Console look like this: 

> /villagerconfig generate
> [09:33:38] [Server thread/INFO]: Starting provider: vanilla/Trades
> [09:33:38] [Server thread/INFO]: An error occurred, please look into the console for more information.
> [09:33:38] [Server thread/ERROR]: An error occurred, while generating trade data
> java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 5
>         at me.drex.villagerconfig.util.TradeProvider.lambda$toJson$3(TradeProvider.java:98) ~[villagerconfig-4.1.21.20.1.i0:0/:?]
>         at it.unimi.dsi.fastutil.ints.Int2ObjectMap.lambda$forEach$0(Int2ObjectMap.java:249) ~[minecraft-1.20.1.i0:0/:?]
>         at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapEntrySet.fastForEach(Int2ObjectOpenHashMap.java:1022) ~[minecraft-1.20.1.i0:0/:?]
>         at it.unimi.dsi.fastutil.ints.Int2ObjectMap.forEach(Int2ObjectMap.java:251) ~[minecraft-1.20.1.i0:0/:?]
>         at me.drex.villagerconfig.util.TradeProvider.toJson(TradeProvider.java:96) ~[villagerconfig-4.1.21.20.1.i0:0/:?]
>         at me.drex.villagerconfig.util.TradeProvider.lambda$run$1(TradeProvider.java:84) ~[villagerconfig-4.1.21.20.1.i0:0/:?]
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
>         at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858) ~[?:?]
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
>         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
>         at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
>         at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
>         at me.drex.villagerconfig.util.TradeProvider.method_10319(TradeProvider.java:85) ~[villagerconfig-4.1.21.20.1.i0:0/:?]
>         at net.minecraft.class_2408.method_46570(class_2408.java:190) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.class_2403.method_46563(class_2403.java:52) ~[minecraft-1.20.1.i0:0/:?]
>         at java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) ~[?:?]
>         at net.minecraft.class_2403.method_10315(class_2403.java:45) ~[minecraft-1.20.1.i0:0/:?]
>         at me.drex.villagerconfig.commands.GenerateCommand.execute(GenerateCommand.java:29) ~[villagerconfig-4.1.21.20.1.i0:0/:?]
>         at me.drex.villagerconfig.commands.GenerateCommand.lambda$builder$0(GenerateCommand.java:21) ~[villagerconfig-4.1.21.20.1.i0:0/:?]
>         at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.class_2170.redirect$fch000$architectury$performCommand(class_2170.java:3545) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.class_2170.method_9249(class_2170.java:287) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.class_2170.method_44252(class_2170.java:280) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.class_3176.method_13941(class_3176.java:299) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.class_3176.method_3813(class_3176.java:284) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[minecraft-1.20.1.i0:0/:?]
>         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-1.20.1.i0:0/:?]
>         at java.lang.Thread.run(Thread.java:1583) ~[?:?]

Afterwards, it generates cleric.json and toolsmith.json but I dont think that is all.

**Comment by DrexHD** [comment]
This is caused by some mods in your modpack registering trades at level 0, which doesn't exist. Villager trade levels start at level 1, so these trades wont show up and cause issues with this mods, which expects trade levels 1 and higher.
Some mods on github that seem to have this problem: [wandering trader level 0 trades](https://github.com/search?q=.registerWanderingTraderOffers%280&type=code). It would be better to report it to the author of these mods to properly fix the issue and make the trades appear.
