### ISSUE TITLE
Trades are empty for new villager types of a mod (TechReborn)

### ISSUE THREAD

**Issue by GPlay97** [DrexHD/VillagerConfig#45]
Hey there,

I executed `/villagerconfig generate` as mentioned in the wiki. It successfuly created the files. I do have a mod installed (`TechReborn`) which also adds two new villager types.
These two villager types are created as dedicated files, which is cool. Unfortunately the trades inside them within the json, is an empty array.

How can I extract the real trades? Is there a way? Can I just add the minecraft ids of the block / items the mod adds?

**Comment by DrexHD** [comment]
Villagerconfig can only generate data for trade "types" it knows. TechReborn uses custom types. I have [submitted a PR](https://github.com/TechReborn/TechReborn/pull/3299) to change this to vanilla trade types, which this mod understands. You can always [manually recreate trades](https://drexhd.vercel.app/villagerconfig/) (the generate command is only for convenience and to understand file structure).
If you just need the files I have generated them using the modified version of TechReborn and attached them below!
[electrician.json](https://github.com/user-attachments/files/17227846/electrician.json)
[metallurgist.json](https://github.com/user-attachments/files/17227847/metallurgist.json)

**Comment by DrexHD** [comment]
PR has been merged and this fix should be included in [5.11.11](https://github.com/TechReborn/TechReborn/releases/tag/5.11.11).
